# Generated by Django 6.0.7 on 2026-08-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshari_app', '0005_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
