# Generated by Django 6.0.7 on 2026-08-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshari_app', '0009_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notify_subscribers',
            field=models.BooleanField(default=False, verbose_name='Notify Newsletter Subscribers'),
        ),
    ]
