# Generated by Django 6.0.7 on 2026-08-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshari_app', '0011_contactmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
