---
deployment:
  tasks:
    - export DEPLOYPATH=/home/osharico/oshari/
    - /bin/cp -R ./oshari $DEPLOYPATH
    - /bin/cp -R ./oshari_app $DEPLOYPATH
    - /bin/cp -R ./templates $DEPLOYPATH
    - /bin/cp -R ./static $DEPLOYPATH
    - /bin/cp ./manage.py $DEPLOYPATH
    - /bin/cp ./requirements.txt $DEPLOYPATH
    - /bin/cp ./build.sh $DEPLOYPATH
    - cd $DEPLOYPATH && /home/osharico/virtualenv/oshari/3.13/bin/python manage.py collectstatic --noinput
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
